CATALOG_MEDICINES = (
    "amoxicillin",
    "amlodipine",
    "artemether-lumefantrine",
    "artesunate",
    "azithromycin",
    "ceftriaxone",
    "ciprofloxacin",
    "co-trimoxazole",
    "doxycycline",
    "gentamicin",
    "glibenclamide",
    "insulin",
    "losartan",
    "metformin",
    "omeprazole",
    "oral rehydration salts",
    "oxytocin",
    "paracetamol",
    "salbutamol",
    "zinc sulfate",
)
